### ISSUE TITLE
glob-parent vulnerability

### ISSUE THREAD

**Issue by TDC9999** [paulmillr/chokidar#1151]
It looks like chokidar is a nested dependency for other libraries, and is quarantined by security scans for a vulnerable version of the further dependency on glob-parent. The newest version of glob-parent fixes this vulnerability. Can chokidar be updated to use the latest version of glob-parent?

**Comment by paulmillr** [comment]
Chokidar does not use vulnerable glob-parent.

**Comment by TDC9999** [comment]
If multiple people are reporting it, there may be more to it than can just be dismissed. I am not attacking you or your project. We did spend time investigating the issue, and our security system is quarantining glob-parent of any version below 6.0.1, including 5.1.2. Even version 6.0.0 is blocked. I can't share a screenshot since it is an internal company system, but every version prior to 6.0.1 is listed as red, critical vulnerability, and is quarantined. I am not the security ops guy blocking it, I am a dev trying to use it, but it is listed as vulnerable and not being allowed. This library is a nested dependency for various other things, including webpack dev server. Is it not possible to update chokidar to use glob-parent 6.0.1?

**Comment by paulmillr** [comment]
No, it is not possible, because it would break nodejs v8 which chokidar supports. 

Your process is definitely wrong. 6.0.0 is vulnerable. 5.1.1 is vulnerable. 

5.1.2 and 6.0.1 are fine. You can check this on various sites.

**Comment by illiakovalenko** [comment]
@paulmillr I have the same issue and inside my company 5.1.2 is reported as a vulnerable version. More than 5-10 people can't be all wrong

**Comment by paulmillr** [comment]
@illiakovalenko then your company has shitty software. Visit https://snyk.io/vuln/npm:glob-parent and check it by yourself.

<img width="814" alt="Screen Shot 2021-12-01 at 8 39 02 PM" src="https://user-images.githubusercontent.com/574696/144293958-bed6db3f-0cb1-4657-bc5f-3f4a66ee3751.png">

**Comment by paulmillr** [comment]
If CVE-2020-28469 affects glob-parent BEFORE 5.1.2, and CVE-2021-35065 affects glob-parent AFTER or EQUAL to 6.0, then 5.1.2 is no vulnerable. Do the math.

**Comment by Flimm** [comment]
Here is my investigation. If you install `glob-watcher` (latest version `5.0.5`), it will install its dependency `chokidar` version `2.*.*` . Currently, all `chokidar` `2.*.*` releases depend on a vulnerable version of `glob-parent`, as far as I can tell. For example, `chokidar` `2.1.8` depends on `glob-parent` `3.*.*`, which are vulnerable to [CVE-2020-284496](https://github.com/advisories/GHSA-ww39-953v-wcq6).

The obvious solution is for `glob-watcher` maintainers to fix `glob-watcher` so that it no longer depends on an insecure version of `chokidar`. Several people reported this issue: https://github.com/gulpjs/glob-watcher/issues/67 https://github.com/gulpjs/glob-watcher/pull/68 https://github.com/gulpjs/glob-watcher/pull/69 Unfortunately, `glob-watcher` maintainers closed these issues as spam. If you try to report the issue again, you are greeted with this template:

> If you are here because `npm audit` or another tool told you there's a vulnerability, please carefully review this template.
> 
> We also see vulnerability issues and regularly review them. If we identify a risk to our projects, we will fix them immediately. When we decide they are not a risk to our projects, there is nothing else we should do.
> 
> Upgrading (when there's not a risk to our projects) is a breaking change to our compatibility matrix and we don't currently take these requests.
> 
> It's uncommon for the npm ecosystem to backport security fixes to older versions that we rely on for our compatibility matrix. It would be a great help to the community if you could contribute a backport on the older release stream of the vulnerable package.
> 
> **If you open an issue like this, it will be closed and locked with no further reason. Continued offenses might result in a temporary ban to keep the noise down in our inbox.**

In other words, `glob-watcher` don't seem to care that they are causing people's `npm audit` logs to be reporting security vulnerabilities. You need to trust them that they are watching and weighing the vulnerabilities, and that they are right to ignore them. (In [this blog post](https://overreacted.io/npm-audit-broken-by-design/), the author argues that this kind of vulnerability doesn't apply in certain contexts. But I don't understand why the vulnerabilities shouldn't be fixed anyway, given that we don't know in what contexts the tool will be used. It's an unnecessary risk.) Personally, I would much prefer everybody to take all security vulnerabilities seriously, instead of training developers to ignore reports of security vulnerabilities and closing reports of security vulnerabilities as spam with no explanation.

If chokidar want to help, I guess they could release a backport of this fix in a `2.*.*` version number.

**Comment by paulmillr** [comment]
If you're using chokidar v2, you may as well be running malware, because we do not have the access to fsevents-v1-binaries aws. Who knows what's been uploaded there.

That's why it doesn't make sense to use v2. It has been deprecated more than 2 years ago. Everyone had plenty of time to upgrade.

The glob-watcher does not want to bump chokidar probably because they support nodejs older than v8. Chokidar 3 is v8+ only.

V3 / fsevents 2 do not use aws for binaries.
