### ISSUE TITLE
Looking for new contributors and maintainers

### ISSUE THREAD

**Issue by paulmillr** [paulmillr/chokidar#1305]
We are looking for folks who are able to:

1. Fix CI tests
2. Simplify the code (#1195)
3. Fix current bugs

Any contributions are highly appreciated.

**Comment by ben-polinsky** [comment]
Hi @paulmillr 

I can take a look at #1 to start.

**Comment by paulmillr** [comment]
@ben-polinsky great!

**Comment by samuelneff** [comment]
I'm new to Chokidar, but recently retired and looking for something to contribute to.

I'll be happy to look at code simplification and at least fix symlink bug https://github.com/paulmillr/chokidar/issues/967. I'm running into issues with that now with [`typed-css-modules`](https://github.com/Quramy/typed-css-modules) [(PR for workaround)](https://github.com/Quramy/typed-css-modules/pull/301).

**Comment by paulmillr** [comment]
@samuelneff nice

**Comment by samuelneff** [comment]
My first PR. 😄 

https://github.com/paulmillr/chokidar/pull/1307

**Comment by samuelneff** [comment]
Did all the tests work at some point? I've fixed two and am looking into a third breaking test.

`should survive ENOENT for missing symlinks when followSymlinks:false`

- Verified the code is doing the right thing and the test had incorrect expectations.
- Since we're not following symlinks then we don't care about the target of the symlink and only treat the symlink itself as a file.
- Even though the target of the symlink doesn't exist anymore, the symlink itself as a file does exist and is a valid file.
- I adjusted the test to match this expectation.

`should watch symlinks within a watched dir as files when followSymlinks:false`

- Fixed underlying issue.
- Readdirp still broadcasts events for watched symlink folders even when we are not following symlinks.
- We want to treat the symlink as a file and ignore any events for contents of the symlink'd folder.
- To do this I'm using the existing _symlinkPaths map to track symlink'd folders for the purpose of ignoring their contents later on.
- This map was previously unused when not following symlinks.

`should detect changes to symlink folders, even if they were deleted before`

- I'm a bit confused by this one so far.
- fsevents dispatches a `root_changed` event when the files inside the symlink are changed but this event isn't handled at all.
- No other events are being broadcast.

I'll look into this one and the others next week. Please let me know if you want a PR for the ones I've worked on so far or if I should hold off until all are fixed.

**Comment by samuelneff** [comment]
@ben-polinsky Sorry I forgot you said you were going to look at CI tests. Have you had time to start yet? We can collaborate if you like. I've worked on the three mentioned above.

You can write to me directly if you prefer; sam@serndesign.com.

**Comment by paulmillr** [comment]
perhaps the best thing to do would be to open a pull request and add Samuel to the fork's collaborators

**Comment by ben-polinsky** [comment]
@samuelneff no problem at all. I only had some time this week to stake a look at `should survive ENOENT for missing symlinks when followSymlinks:false` and came to the same conclusion as you. Didn't test on older versions of node, but did test on both M1 and Intel macs (same result).

Happy to work on the DTS Linting issue if you haven't started.
