### ISSUE TITLE
stats are not being sent in all cases

### ISSUE THREAD

**Issue by mlakkadshaw** [paulmillr/chokidar#205]
I noticed that the stats object is not sent in all cases, for instance when we rename a directory even sometime when adding files when chokidar is running, the stats object for those files are not being sent to the add event listener, only the path is being sent.

Thanks

**Comment by es128** [comment]
That's sort of by design. Chokidar passes the stat object when it has it, but does not eagerly make stat calls that may or may not be needed when it doesn't (which can happen in several ways). 

You can just do your own `fs.stat` call if you need it and chokidar didn't pass it along. 

On the other hand, an `alwaysStat` configurable option may be a worthwhile enhancement so you don't need to do that if intend to rely on the stat data (and are willing to accept the minor perf penalty)

**Comment by mlakkadshaw** [comment]
Got it, Thanks, I will implement alwaysStat option.
