### ISSUE TITLE
permanent watch and 'too many event listener'

### ISSUE THREAD

**Issue by jeromeetienne** [paulmillr/chokidar#232]
Hello, i need a permanent watch a given directory, all is going well it seems. 

but after a while it keeps complainaing about "too many event listener…" 

is that to be expected ? or do i have a bug ?

**Comment by es128** [comment]
Depends on what you're doing in your code. Chokidar return an instance of node's native EventEmitter class. You can read more about that at http://nodejs.org/api/events.html. Sounds like you may want to make use of the `setMaxListeners` method.

If you think you may have encountered a bug, you'll need to provide a much better description and preferably provide code and steps to reproduce in order to get help with it here.

**Comment by jeromeetienne** [comment]
thanks :)
