### ISSUE TITLE
stat.size sometimes reports 0 on a changed file that has contents

### ISSUE THREAD

**Issue by jessehattabaugh** [paulmillr/chokidar#270]
I have a watch script that watches all my js files for changes and runs a build process. 
```
chokidar.watch(path.join(config.src, '**/*.js'))
    .on('change', function (path, stat) {
      if (stat.size) buildProcess();
    });
```
It works.. usually. 

Sometimes stat.size == 0 even though the file has contents. If I delete a line from somewhere in the middle of the file and save, suddenly the filesize reports correctly. There's nothing special about the characters on that line, sometimes they are Javascript statements, sometimes inert comments. If I go about my work eventually the problem recurs, but not with any regularity. I'm using Codeanywhere which is Ubuntu.

**Comment by es128** [comment]
The `stat` object comes directly from node's `fs.stat` - I don't think there's anything that can reasonably be done in chokidar to fix this.

It's probably occurring because of a race condition with the way your editor saves files. In your own logic, you should probably just do your own `fs.stat` call after a slight delay to double check the result if you got 0 with the `change` event. 

Also, not sure why you're checking `stat.size` to begin with - if a file is emptied, wouldn't you need a rebuild anyway?

**Comment by jessehattabaugh** [comment]
I do the check because, nearly every time I save a file, two change events
fire. The first has stat.size: 0. The second is typically correct, so I
just ignore those. Maybe I should just debounce instead of checking
stat.size.

**Comment by es128** [comment]
Chokidar already does a bit of debouncing on `change` events, so if you're getting two every time the editor must be very slow to complete its write operation.

So yeah, there's various approaches you could take on your end to resolve this, but I don't think there's anything actionable to do here with chokidar. Closing the issue for now.
