### ISSUE TITLE
Inconsistent change detection

### ISSUE THREAD

**Issue by markfinger** [paulmillr/chokidar#280]
Hi,

I've been using chokidar for invalidation of files, and I'd been experiencing quite flakey unit tests where watched files would not have changes detected within a second or two and the test would fail. I ended up fixing the issue by adding a random file to the watcher before starting the tests.

For context, between every test I would close the watcher, then create a new instance of `FSWatcher` and use that within a few milliseconds of having closed the previous one. All I can assume is that perhaps there's a warmup of some sort which might only complete after the test starts and the changes get lost...?

Am I doing something wrong, or is this a necessary hack to get around OS-level weirdness?

-------------------

```
// Before each test creating a new watcher
var fileWatcher = new chokidar.FSWatcher();
fileWatcher.on('change', onFileChange);

// ...

// Files are watched during test cases via:
fileWatcher.add(filename);

// ...

// After each test case I close the watcher
fileWatcher.close()

// The next test case causes a new FSWatcher to be created
```

Changes would be inconsistently detected despite synchronous writes occurring after the call to `add`. Calling `fileWatcher.add(module.filename);` before every test case seemed to fix the issue.

Random tests involving the filewatcher would fail every 1 in 2 runs, now they pass every run.

-------------------

OS: OSX 10.10.2
Node: v0.12.0

I've been experiencing this with a bunch of different versions of chokidar up to and including 1.0.1.

--------------------

Cheers for writing the lib :+1: 

- Mark

**Comment by es128** [comment]
By operating on files and listening for change events within the same process you create inherent race conditions, and it is necessary to wait a sufficient amount of time before asserting that an event should have been received. It is important to recognize that these are not *unit* tests unless you mock out `fs` and `fsevents`. They are integration tests involving the entire stack supporting the file watching underneath, and inconsistent behavior can often be observed there. 

Chokidar's tests struggle with this too, and there's a lot of fine tuning on the delay intervals that happens there. I've improved this a lot over time and gotten the tests to run way faster than they used to, but there are still sporadic failures (false negative) on Travis because of the underpowered VMs used there. 

You haven't shown enough code for me to know what kind of delays you're allowing for now, but one thing I am noticing is that you're not listening for the `ready` event. It may be helpful to do your `fs` operations in a `ready` listener. However, it would be necessary to spawn entirely new watcher instances like chokidar's tests do rather than closing and reopening the same one in order to leverage this as `ready` is emitted once per instance. Arguably, that could be reset after `.close()`, but this is the current behavior.

**Comment by markfinger** [comment]
Thanks for all the info!

If a `ready` event is triggered and I add another file located in another dir, could I still rely on the `ready` state for the newly added files, or should I ensure that they are all added in one batch and then wait for `ready`?

**Comment by es128** [comment]
`ready` is useful with the `.watch()` method, not so much with `.add()`. You can pass an array to `.watch()` to describe everything you want watched by this instance. The event indicates that the initial scan of the file trees you are watching is complete, and it likely `ready` would have already been emitted before you have a chance to `.add()` anything else.

**Comment by markfinger** [comment]
Cool. So if you wanted to ensure reliability when adding a new file, it would be best to stop the current watcher, create a new watcher instance, add all the current files and the new one, and block until `ready`?

**Comment by es128** [comment]
Yeah in a testing situation that's reasonable.

In a typical situation there typically isn't a need to jump through these hoops as external forces are driving the change events, so there's no specific timing expectation. 

In your case you may find it easier (and may find it necessary even if you refactor) to set some artificial delays before you make assertions. 

If you haven't looked at how chokidar's tests are structured, I'd suggest you do that.

**Comment by markfinger** [comment]
Cool, thanks for all you help!
