### ISSUE TITLE
Change event fired twice, is it by design?

### ISSUE THREAD

**Issue by bitinn** [paulmillr/chokidar#298]
I am new to chokidar, can you spot any problem with this simple usage of chokidar?

https://github.com/bitinn/wiper/blob/master/lib/wiper.js#L70-L81

		self.watcher = chokidar.watch(list);
		log('started watching files: ' + opts.w.join(', '));

		self.watcher.on('all', function(event, file) {
			log(file + ' was ' + event);
			
			self.server.changed({
				body: {
					files: file
				}
			});
		});

I use it to watch my browserify output bundle, which then trigger livereload server to reload. But chokidar seems to fire `change` event twice consistently (same file name and event name), so livereload is triggered unnecessarily.

my build command: `browserify components/client-js/main.js -s app -o public/assets/app.js`. I can verify my command only ran once.

**Comment by bitinn** [comment]
I tried to throttle it by adding a callback to wait for previous livereload to be done. But that second change event often comes at around 1-2s after initial change event, which means livereload is done by then, so it didn't work for me...

**Comment by es128** [comment]
See if using a different editor or repeating the same actions on a different system has any impact. It's likely that *something* is actually touching the file again after you edit it. Could be something you don't expect like antivirus or a backup solution. 

It is definitely not by design, and chokidar already has built in throttling for duplicate events that show up close together. But a 1-2 second difference is too much to be automatically suppressed like that.

**Comment by bitinn** [comment]
@es128 It's likely due to `browserify` touching the file multiple times (but really I don't know why it decides to touch it twice and 1-2s apart)

Editing with sublime text or `nano` doesn't seem to cause chokidar to fire change event twice.

So I guess it's one more thing I need to handle myself, I have set a 5 seconds throttle on livereload as a workaround.

**Comment by tnguyen14** [comment]
I ran into this issue recently with using `vim` as the editor as it does a backup write. It seems that `watchr` figured out a way to solve it https://github.com/bevry/watchr/issues/33. Could this be solved here as well?
