### ISSUE TITLE
Memory Issues

### ISSUE THREAD

**Issue by weagle08** [paulmillr/chokidar#307]
FSWatcher objects seem to not be destroyed when a file is 'unwatched', or when the file is deleted from a watched directory. Is this by design?

**Comment by paulmillr** [comment]
I don't think so. Did you have any real problems? We'll need to investigate this.

**Comment by es128** [comment]
It is by design in many situations. For a file that's deleted, watching is definitely persisted in case it comes back.

For `unwatch` it depends on what the watch target was to begin with. Sometimes you're `unwatch`ing a subset of what's being watched by a particular underlying watch method.

As @paulmillr said, a more concrete example needs to be provided if you think there is a problem.

**Comment by es128** [comment]
Here's the code for the unwatch method: https://github.com/paulmillr/chokidar/blob/ba90462886d0fbb1927f70fe2e7a25a4249b9994/index.js#L430-L448

You can see that it either closes the underlying watch instance if there is one, otherwise it just treats the unwatched path as something to be ignored.

And actually, if your concern is the chokidar `FSWatcher` instance itself, then yes it is definitely by design that it does not get destroyed because users might want to `.add()` something else after the `unwatch`.

If you want to clean up memory, you should use the `.close()` method.

**Comment by weagle08** [comment]
Ok, this is a misunderstanding on my part because yes the files I am calling unwatch on are still in the top level directory path which I am watching. In this case I'd say the library is working as expected, however would you guys know of a library or way i can watch only a directory tree for adds/deletes, and not care about the actual file changes?

**Comment by es128** [comment]
Listen to the `add` and `unlink` events only. Ignore the `change` events.

**Comment by weagle08** [comment]
Yes, but our problem is memory consumption caused by all the FSWatcher objects created because of the number of files in the directory we are watching. Is there a way to tell the library to destroy these for files and only watch directories?

**Comment by weagle08** [comment]
So some numbers: my node process with no files in my watched directory and nothing else happening in the system: ~50,000KB of memory, add in 10,182 files and the memory jumps to 340,160KB of memory, stop the node process and start it back up watching this same directory and the memory is less at 163,180KB but this is still ~16KB of memory per  file being watched!!! Seems very high even for just one FSWatcher object per file. I definitely think there is a memory issue.

**Comment by es128** [comment]
What OS are you on, and what settings are you using for chokidar?

**Comment by weagle08** [comment]
Ok, ran with the exact code below:
```
    var express = require('express');
    var chokidar = require('chokidar');

    var dataWatcher = chokidar.watch('C:/testData', {
        persistent: true,
        ignoreInitial: true
    });

    dataWatcher.on('add', function(file){
        console.log('added file: ' + file);
    });

    var app = express();
    app.listen(8080, function(){console.log('express server running')};
```
    
Start up: 23,068KB
Dropped 10,182 files: 155,904KB
Restart: 144,424KB

so ~12KB/file

**Comment by weagle08** [comment]
Also tested to see what the .NET directory watcher used in comparison and it was less than 1KB per file.

**Comment by es128** [comment]
The short answer is no, chokidar does not provide an option to skip file-level watching. There may be a way to manipulate chokidar into doing this with some clever glob or ignoring settings, but if you only need to target Windows and only need to watch the one directory (no recursion), it may work out better for you to just use `fs.watch` directly for this use case.

The memory usage you're observing is likely related to the separate watcher instances per file as you've observed, which is necessary to reliably pick up the file events chokidar is observing (including `change`), and the fact that an `fs.Stat` is collected for each entry to differentiate between files and dirs. I've discussed the possibility of improving performance using alternate means of scanning the file tree at https://github.com/thlorenz/readdirp/issues/24, but so far have not been able to spend any time trying to implement that idea.

**Comment by weagle08** [comment]
Thank you for the explanation! Preferably I would like to support both windows and linux and it seems that fs.watch will suffice for this... If I've read fs.watch documentation correctly the problem OS is OS X because it handles file system events differently. Is this correct?

**Comment by es128** [comment]
The main issue you're likely to encounter is that the events on a dir-level watcher on OS X won't provide the filename of the impacted file.

There's all sorts of other inconsistencies about `fs.watch` on any OS (largely the reason chokidar exists), but I haven't ever focused on a use case like yours where you're not interested in `change` events. Even for `add`/`unlink` though, Chokidar has to double-check what the system reports by reading dir contents upon an event being reported.  YMMV

It may be possible to add an option to chokidar that skips the file-level watching and otherwise retains the consistency benefits. If you encounter trouble with `fs.watch`, let me know if you'd be interested in pursuing this feature.

**Comment by weagle08** [comment]
yeah, def will do. Thanks a lot for the help.
