### ISSUE TITLE
`ignored` option not working?

### ISSUE THREAD

**Issue by freder** [paulmillr/chokidar#321]
hi,

I want to ignore the `.git` dir in the root of the watched dir, but I found that the `ignored` option has no effect. — I tried a number of things:

```javascript
var config = {
	persistent: true,
	ignoreInitial: true,
	followSymlinks: false,
	ignored: [
		'.git',
		'.git/**/*'
		'./**/.git/*',
		'./**/.git/**/*',
		'.git/**/*',
		/\.git/ig,
		/\.git/,
		function(p) {
			if (mout.string.contains(p, '.git')) {
				return true;
			}
			return false;
		}
	]
};

var watcher = chokidar.watch([thePath, '!'+path.join(thePath, '.git')], config);
```

`os x 10.10.4`
`chokidar 1.0.5`

or am I missing s.th. here?

**Comment by es128** [comment]
Can't spot an issue with the example code provided (aside from all the redundancy, but it should be harmless).

What happens if you clone the chokidar repo and run the `example.js` script? `ignored` is working fine for me in that case.

What event(s) are you listening to? `ignored` does not apply to the `raw` event.

**Comment by freder** [comment]
the `example.js` works as expected.

also – I'm not sure why – but `ignored: [ /\.git/ ]` seems to work now all of the sudden. :hushed:
