### ISSUE TITLE
"unlinkDir" not firing

### ISSUE THREAD

**Issue by Dorosty** [paulmillr/chokidar#337]
On Ubuntu 14.04 the following code works when I add, modify or remove a file in the "src" directory. However when I remove a directory from it (for example "src/a"), "unlinkDir" does not fire. Am I doing something wrong?

``` javascript
var watcher = chokidar.watch('src/**/*.coffee');
watcher.on('add', compile);
watcher.on('change', compile);
watcher.on('unlink', remove);
var dirWatcher = chokidar.watch('src/**');
dirWatcher.on('unlinkDir', removeDir);
```

**Comment by es128** [comment]
The glob pattern `src/**` appears to be matching only the files, not the directories. This will work if you just watch `src` with `dirWatcher` - only listening to `unlinkDir` and/or `addDir` will filter the events to only dir-level events as you intended (at least based on my quick local testing that appears to be the case).

The pattern seems like it *ought* to match the subdirs, so what needs to be investigated is why they're being filtered out in this example.

**Comment by danbucholtz** [comment]
@es128,

I have a similar situation as @Dorosty but it is ever so slightly different.

I have a watch on some files of a given extension, in my case, `.ts` from a glob (`**/*.ts`). If I am listening for `all` events, and I delete a directory containing the a `.ts` file that meets the glob criteria, I do not receive an event.

For example,

I'm watching all `.ts` files in `src`. If I delete `src/someDir` which contains `src/someDir/someFile.ts`, I do not receive an `unlink` event for `someFile`.

This does not seem like an expected behavior to me. What do you think?

Thanks,
Dan

**Comment by es128** [comment]
@danbucholtz sounds like a bug that's not necessarily related to the resolved one from this issue. 

Could you please file a new issue and include details like version, OS, and which options are being used?

**Comment by danbucholtz** [comment]
@es128, will do. Thanks!

Thanks,
Dan
