### ISSUE TITLE
Separate flag for globs

### ISSUE THREAD

**Issue by paulmillr** [paulmillr/chokidar#370]
Let's consider adding this to 2.0. Maybe `glob: false` should be the default value.

We have a lot of related problems. Folks are not aware that the first argument is actually glob. See issue list.

**Comment by es128** [comment]
I disagree. Which issue(s) are related to people not understanding that the first arg can be a glob? At this point I think the majority of users are relying on globs rather than just direct file/dir paths.

There's an issue when actual dirs use special characters in them, but there should be a transparent solution to that (first check on disk for an entry that matches the input, even if it happens to use glob-significant characters)

Your suggestion seems similar to #347, and I remain very :-1: on the idea.

**Comment by TrySound** [comment]
:-1:

**Comment by es128** [comment]
I have relented. #598
