### ISSUE TITLE
Watcher.add() and CPU 

### ISSUE THREAD

**Issue by rfossella** [paulmillr/chokidar#433]
I initially watch a collection of folders.  About 400 folders with 10,000 files.
```
var watcher = chokidar.watch(folders, 
					{	ignored: /[\/\\]\./, 
						persistent: true,
						usePolling: true,
						interval: 1500,
						binaryInterval: 2500
					});
```
I am watching files over a network and per recommendation it seems I have to **usePolling:true** .  I would still love to be able to stop using polling but it simply does't work

So, my question: after node starts and setting up watcher my (Windows) CPU will hover between 8-20%.

Later I will adhoc add 20+ folders using **watcher.add(newFolder)** inside a loop.  Folders get added but the cpu jumps to 30-50% and it stays at that range for a long time.

So, is there a better way to add folders to the current watcher instance?  Any chance I can turn polling off while watching network files.

BTW, when I have my server running throughout the night sometimes the CPU and memory causes system crashes.   Ideas?  Any direction for better approach using chokidar? **thank++you**

**Comment by es128** [comment]
Unfortunately, I don't suspect there is any good way to improve the situation trying to watch that big of a file tree over a network mount. 

I'd suggest you take a step back and try to find ways to run your processing on the same machine where the files live in order to be able to use more efficient means of watching. If there's some barrier to fully moving where you run your program, perhaps you can set up a daemon-style process running where the files are that communicates signals over the network to your main process running on the windows machine. Or perhaps some other means of copying and syncing all the files locally and watching the local copies.
