### ISSUE TITLE
Path is missing a slash

### ISSUE THREAD

**Issue by joepb** [paulmillr/chokidar#439]
When watching `'./sources/**/*.ts'` I have a file called `C:\(...)\sources\apis\client.ts` but the vinyl.path of the watch shows `C:\(...)\sources\apisclient.ts`. Missing the last slash.

**Comment by es128** [comment]
Can you please describe how you've narrowed this down to find that it is an issue with chokidar?

**Comment by joepb** [comment]
It could be a deeper problem, but I occurs with a watch created on Chokidar:

    chokidar.watch('./sources/**/*.ts').on('change', function(path) {
        console.log(path);
    });

that piece of code returns the paths without the last slash.

**Comment by joepb** [comment]
Didn't mean to close the issue. Just missed the button by 10 pixels :)

**Comment by es128** [comment]
Please add a listener to the `raw` event to that bit of code and post the results of what's being emitted when you make changes to those files.

**Comment by joepb** [comment]
Quite odd. I can't seem to reproduce it anymore... As soon as I find the correct conditions, I'll reopen.

Thanks.

**Comment by steinhaug** [comment]
I just installed chokidar as a possible workaround for some event errors with gulp.watch, and I am using the CLI version and I get the same problem. I am on a windows system and init like this:

    chokidar 'public_html/**/*.php' -c "echo {path}"

When a PHP file is updated I get the following output:

    change:public_html\info.php
    public_htmlinfo.php

The / is missing from the {path} element, so I cannot use the -c parameter and pass the filepath into a function for copying.

Could it be that windows defaults to \ as directory seperator instead of / which escapes it and that is the reason it is gone?
