### ISSUE TITLE
Event trigger sequence error

### ISSUE THREAD

**Issue by nuintun** [paulmillr/chokidar#445]
I use webstorm, when I modify a file,
It will trigger ```unlink``` event after ```change``` event sometimes!

**Comment by es128** [comment]
Please log the `raw` events to see what's happening underneath and whether chokidar is reacting incorrectly. Also need details about your system, options, versions, etc.

Closing the issue for now as there is nothing to investigate, but may reopen if you can provide better evidence to check into.

**Comment by nuintun** [comment]
I got the error again!

Watch code:
```js
// file watch
function watch(glob, options, callabck){
  if (typeof options === 'function') {
    callabck = options;
    options = {};
  }

  // ignore initial add event
  options.ignoreInitial = true;

  // get watcher
  var watcher = chokidar.watch(glob, options);

  // bing event
  if (callabck) {
    watcher.on('all', callabck);
  }

  watcher.on('raw', function (event, path, details){
    console.log('    Raw event info:', event, path, details);
  });

  // return watcher
  return watcher;
}
```

screenshot:
![qq 20160304102730](https://cloud.githubusercontent.com/assets/1730277/13516390/b708b5d6-e1f4-11e5-9d12-997c9255b0d1.png)
![qq 20160304102805](https://cloud.githubusercontent.com/assets/1730277/13516393/b93bfa5c-e1f4-11e5-8078-4feefa70d2e0.png)

**Comment by es128** [comment]
> need details about your system, options, versions, etc.

**Comment by nuintun** [comment]
@es128 

System: Windows 10 Pro Insider Preview
Version: 1511(Build 14271.1000)

Chokidar version: v1.4.3
Chokidar options: ```{ ignoreInitial: true }```

**Comment by es128** [comment]
The `unlink` events emitted by chokidar are happening after raw `change` events being emitted at the directory level. This triggers chokidar to do a `readdir` on the directory and compare the contents to its memory object representing the file tree. The file is not being returned with the `readdir` results, which means that it is not there at the time - likely temporarily because of webstorm's behavior. Chokidar tries to correct for these situations, but the timing appears to not work out in your case. 

Your potential remedies are to use the `usePolling: true` option or look into and tweak webstorm's options regarding file writing behavior.

**Comment by nuintun** [comment]
@es128 3Q~
