### ISSUE TITLE
Is there a reason for the 128 FSEvents watcher limit?

### ISSUE THREAD

**Issue by ashaffer** [paulmillr/chokidar#482]
It's forcing my project to fall back to polling for a lot of the files I need to watch, which is making it quite slow. I tried stubbing it out so that it always returns true, and it seems to work just fine. Is there a reason that limit needs to be there?

btw: Talking about the `canUse` in `lib/fsevents-handler.js`

**Comment by es128** [comment]
Some history for why this was implemented at https://github.com/substack/watchify/issues/106. There's an absolute system limit on OS X (last I checked) of around 450 FSEvents across all processes. 128 was  a somewhat arbitrary limit set to account for a few instances of chokidar being able to run before tripping the `CarbonCore.framework` errors.

Since recursive watching is nearly free in terms of resource utilization under FSEvents, chokidar tries to consolidate those underlying watcher instances to common parents, even if as a user you're asking for lots of watcher instances on different paths. 

What does your watch config look like that you're managing to even hit the 128 limit to begin with? When you stub `canUse` to `return true`, can you also log out the count how many instances you're managing to reach?

**Comment by ashaffer** [comment]
In my project at the moment it seems to make its way up to 224 listeners. This seems to be proportional to the number of modules I happen to have `npm link`'d at the time. Is there some reason that would cause extra watchers to be created?

**Comment by es128** [comment]
> seems to make its way up to 224 listeners

So if the limit weren't in place and you were to run two instances of this process, or grow the project to the point where you make your way into the 400s, you'd end up in territory where catastrophic failures happen in your process(es) that chokidar could not do anything to help you resolve.

> number of modules I happen to have npm link'd at the time. Is there some reason that would cause extra watchers to be created?

Yes! The symlinks are being followed to their destination and a separate watcher being opened on each. If you were to explicitly add a watcher on the common parent of where the linked modules live on your file system - could be a separate watcher that you don't bind event listeners to - I believe you'd eliminate the problem you're observing.

Some ideas about a generalized fix:

* Make that 128 limit configurable. But I don't like this, it's a band-aid that would only help in fairly narrow circumstances. There's no working around the 400-something system-wide limit afaik. And it exposes a new config element to users that's hard to contextualize, and I think would often be found confusing and/or misused.
* Pick another arbitrary limit of fsevents instances (30?) at which point run some logic on the watched paths looking for common parents to reduce to - using the existing shared instance mechanisms. This is like an automated version of the workaround I suggested to you above.

**Comment by ashaffer** [comment]
I think option 2 makes the most sense. The overwhelming majority of my watches paths are just node_modules, and right now for some reason it doesn't figure out that it can just watch the `node_modules` folder and instead watches each individual module. Fixing that would dramatically reduce the number of watchers for me. And I assume this problem is probably effecting other people, they just don't notice that it's causing high CPU utilization.

**Comment by es128** [comment]
Right, if there's already a watcher on a parent of a new watch that's being requested, then it reuses that, but it doesn't currently try to recognize that it's being asked to watch a whole bunch of siblings individually.

**Comment by ashaffer** [comment]
Alright, i'll try to make a PR for it. The algorithm is a little bit tricky I realize though. You don't want to *over* consolidate, because then you'll get notified for too many events.

For instance, say you have:

`/Users/me/proj1/...
`/Users/me/proj1/node_modules/symlinked_thing/...`
`/Users/me/symlinked_thing/...`

Applying a naive common parents algorithm, you end up watching everything in `/Users/me` which is overbroad. What you really want is to reduce this to `/Users/me/proj1` and `/Users/me/symlinked_thing`, I assume. Unless you think the overbroad watching would not be a problem?

**Comment by es128** [comment]
It is important to avoid being overbroad. Not doing so means you'll end up watching the entire filesystem in cases, and we don't want that. I think a starting point can be to just keep track of the immediate parent of paths being watched, and if it gets to a point where `n` of them match, consolidate. Should cover any similar `npm link` type of case.

I realized that the workaround I had initially suggested actually isn't great because it will cause chokidar to walk that entire parent directory unnecessarily. Confining this to the fsevents instance sharing logic should be effective though.

**Comment by ashaffer** [comment]
Hmm...is there a good way to consolidate watchers without breaking their close handlers?

**Comment by es128** [comment]
This wouldn't be happening using the public API, just in the underlying wiring. Take a look at the `setFSEventsListener` function. At least an instance that watches the common parent can be kicked off easily in case of any additional siblings. 

Consolidating the already-established instances would be trickier, but I think it can be done by taking their listeners and re-registering them on the parent (with a `filteredListener` wrapper).

If there isn't a clean way to pull that off, then maybe the jump to the parent should happen at a lower limit, like perhaps 10, and the original set of instances prior to determining the need to consolidate would be left alone.

**Comment by ashaffer** [comment]
Ya that's what i'm looking at. The issue is that `setFSEventsListener` returns a `close` function, which refers to the closure of the original watcher instance.

**Comment by es128** [comment]
Ah, I see what you mean. Maybe something like an empty object reference can be put in there that can be updated later during consolidation to move the close actions to the right place. But yes, seems messy. I'd start with the simpler idea just to validate the concept and then see about making it more efficient.
