### ISSUE TITLE
Installation of fails on node 5 and node 6 linux

### ISSUE THREAD

**Issue by StephanBijzitter** [paulmillr/chokidar#504]
See: https://github.com/strongloop/fsevents/issues/138

**Comment by paulmillr** [comment]
Yeah, it's supposed to fail. Optional dependency.

**Comment by StephanBijzitter** [comment]
@paulmillr Here's the full log of `npm install --no-optional`:
https://gist.github.com/StephanBijzitter/1d4ba9cdb2d9f15c4a77b9b36c758e7b

**Comment by paulmillr** [comment]
Chokidar has 5 million monthly installs. Why did no one brought it over? I suppose something is wrong with your environment.

**Comment by es128** [comment]
If you're using a shrinkwrap file and sharing across platforms, extra care needs to be taken because it can cause this problem. It's an npm bug: https://github.com/npm/npm/issues/2679

**Comment by davidgilbertson** [comment]
chokidar: 1.6.1
node: 6.6.0
npm: 3.10.3
macOS: 10.12.1

Did something change with this recently? Shrinkwrapping had been fine for me (building on macOS, deploying on Linux) as long as I do `npm install --no-optional`. I have `nodemon` in my `devDependencies` which has `chokidar` as a dependency.

But now, even if I do `npm install --no-optional --ignore-scripts`, I get `fsevents` installed by `chokidar`, and what's odd is if I look at `node_modules/chokidar/package.json`, it lists `fsevents` not as an optional dependency but an actual dependency:

```json
  "dependencies": {
    "anymatch": "^1.3.0",
    "async-each": "^1.0.0",
    "fsevents": "^1.0.0",
    "glob-parent": "^2.0.0",
    "inherits": "^2.0.1",
    "is-binary-path": "^1.0.0",
    "is-glob": "^2.0.0",
    "path-is-absolute": "^1.0.0",
    "readdirp": "^2.0.0"
  },
  "description": "A neat wrapper around node.js fs.watch / fs.watchFile / fsevents.",
  "devDependencies": {
    "chai": "^3.2.0",
    "coveralls": "^2.11.2",
    "graceful-fs": "4.1.4",
    "istanbul": "^0.3.20",
    "mocha": "^2.0.0",
    "rimraf": "^2.4.3",
    "sinon": "^1.10.3",
    "sinon-chai": "^2.6.0"
  },
  /// bunch of stuff
  "version": "1.6.1"
```

What has the ability to change a `package.json` like that (so that it's different from what I see in your repo with the `1.6.1` tag?)

Is there a specific set of steps I should be taking (to shrinkwrap on macOS to deploy on Linux)? I'd be happy to do a PR to put them in the readme if you like.
