### ISSUE TITLE
Glob don't match pattern start with "!./"

### ISSUE THREAD

**Issue by dungdm93** [paulmillr/chokidar#537]
Example I have a directory:
```
src
|- index.js
|- spec.js
\- feature.js
```

I want to watch all js file under `src` except `index.js`
```js
var watcher = chokidar.watch(["!./src/index.js", "./src/**/*.js"]);
// watch spec.js, feature.js and even include index.js
```

If change a little bit like this, everything work fine.
```js
var watcher = chokidar.watch(["!src/index.js", "./src/**/*.js"]);
```
I have checked with [`is-glob`](https://www.npmjs.com/package/is-glob), `!./src/index.js` is also a valid glob.

**Comment by es128** [comment]
Looks like you already solved the problem. What are you looking for out of this issue report? Better awareness of unnecessary leading `./` for relative paths in the glob matching? You could report it to [micromatch](https://github.com/jonschlinkert/micromatch), but you could also just stop using `./`.

The only thing is-glob is telling you in this case is that there is a `!` in the string, not whether your pattern will successfully match the way you want it to.

**Comment by dungdm93** [comment]
I think it's a bug, isn't it? Because why must we stop using `./` while it's valid pattern.

**Comment by es128** [comment]
I'm not sure that it should be considered a bug. Relative paths coming from `fs.readdir` do not come with `./`, so your pattern doesn't match the way you want it to. You keep asserting it's a valid pattern, but in what regard? Valid syntax? Shouldn't the criteria be whether it matches the file paths you want it to? 

Feel free to submit a PR that automatically resolves the confusion that can be caused by user-entered `./`

**Comment by jonschlinkert** [comment]
fwiw I'm pretty sure that glob and minimatch will not match the leading `./` either. related: https://github.com/isaacs/minimatch/issues/30

aside from that, `./` is completely unnecessary in the glob pattern. IMHO it's not a bug, just something that needs to be discouraged.
