### ISSUE TITLE
Not triggering on hidden (dotfile) files

### ISSUE THREAD

**Issue by andersevenrud** [paulmillr/chokidar#577]
Hi,

I'm having some issues with chokidar and listening with a glob-pattern. It seems that nothing happens when I manipulate files inside directories with a leading dot (aka. hidden in NIX). Example: `/data/storage/**` (any glob-pattern seems to fail).

However, when I just listen on `/data/storage` it seems to trigger exactly how I want.

Since I'm using this behind an application with dynamic/configurable paths (in which case glob patterns is really handy) this is bit of a problem.

Is this a bug, or am I simply using wrong pattern? I've tried lots of stuff, but simply can't get it to work.

An example of a path that fails under my conditions: `/data/storage/anders/.something/here`

```
Node v7.4.0
Arch Linux
```

**Comment by es128** [comment]
Globs ignore dotfiles by default as a feature. There is an option in micromatch to change that, but unfortunately it's not exposed through chokidar.

You could watch `/data/storage` as a directory instead of a glob, and then create a function for the `ignored` option that does the filtering you want (potentially using micromatch with the `dot: true` option in order to keep using the same glob patterns).

**Comment by andersevenrud** [comment]
That's what I though.

Thanks :)

**Comment by feifeipan** [comment]
Thanks.

ignored: mm.makeRe("node_modules|\.DS_Store|pom.xml",{dot:true})
