### ISSUE TITLE
Use "recursive" option to fs.watch() on darwin

### ISSUE THREAD

**Issue by rcombs** [paulmillr/chokidar#629]
This provides recursive watching when the `fsevents` module is unavailable, and should allow users to avoid polling (which is extremely expensive) in that case.

**Comment by es128** [comment]
It's already possible to force `fs.watch()`-based watching on OS X with `useFsEvents: false, usePolling: false`. Polling is the fallback to the default because `fs.watch()` reliability on OS X was extremely poor historically. I haven't evaluated it lately.

Using the `recursive` option where available would require significant restructuring to the nodefs-handler.
