### ISSUE TITLE
Cannot watch multiple not-yet-created files within the same directory

### ISSUE THREAD

**Issue by bard** [paulmillr/chokidar#639]
The following does not work:

```
$ cat test.js
const chokidar = require('chokidar')

chokidar.watch(['dir_A/foo', 'dir_A/bar']).on('all', (event, path) => {
  console.log(event, path)
})

$ mkdir dir_A
$ node test.js &
$ touch dir_A/foo
add dir_A/foo
$ touch dir_A/bar
$
```

An `add` event is reported for `dir_A/foo` but none for `dir_A/bar`.

However, if I replace `dir_A/bar` with `dir_B/bar`, i.e. the second file isn't in the same directory, it works.

There is a test for watching a non-existent file (https://github.com/paulmillr/chokidar/pull/163/commits/114fab1d82db95ca6f3490e9bed05669de3f315a), so I take that chokidar wants to support the use case, but that test only watches one file and therefore does not incur in the problem above.

#435 is probably related but it doesn't offer a solution, only a workaround (which unfortunately won't help in my case).

**Comment by laurelnaiad** [comment]
Any time the watches are not in the control of the developer, the workaround offered in #435 can be insufficient. I've got a case where my user will configure the system such that files which happen to be in the same directory will end up being added to a watch list... gonna look around for alternatives, since #435 casts some doubt on whether this circumstance is going to be considered for a fix.

**Comment by plexigras** [comment]
i have the same issue is there a solution to this?

**Comment by arielshaqed** [comment]
I am also running into the same issue.  (Not sure how to make this issue popular other than +1 it here with another comment, sorry).

**Comment by theprimone** [comment]
+1, when I use chokidar in WSL 2. Workaround by map files to watchers https://github.com/vitjs/vit/blob/master/packages/vit/src/index.ts#L46
