### ISSUE TITLE
Issue with absolute path under windows 10

### ISSUE THREAD

**Issue by antoineVgs** [paulmillr/chokidar#668]
Hello,

I'm facing an issue since upgrade to 2.0.0 on windows 10.
call to function
```
const chokidar = require('chokidar');

chokidar.watch("D:\my-library\app/**/*.ts").on('all', (event, path) => {
      console.log(path);
  });
```
the console.log is never called when editing a file despite it was working on version 1.7.0.

I had a look in the code, and it seems that in index.js l.420:
globFilter(resolvedPath); is returning false when called with a ts files whereas it should return true.

Please note also that if I called chokidar.watch() with a relative path instead of the global one, it works.
```
chokidar.watch("D:\my-library\app/**/*.ts") **fail**
chokidar.watch("app/**/*.ts") **succeed**
```

**Comment by remy** [comment]
I'm seeing the same too. It's down to the move to anymatch@2 who dep micromatch switches to using backslashes, which means that on windows the `_isIgnored` nearly always fails.

I've got a fix in the works and will offer up a PR to the chokidar folk.

**Comment by es128** [comment]
@antoineVgs you cannot use `D:\my-library\app/**/*.ts` with chokidar 2 as it is technically an invalid glob and we have upgraded our globbing libs. It was necessary to sacrifice the flexibility we used to have here in order to enhance functionality with things like escape characters in globs. This is the reason for the major version bump.

If you want to use globs, you must ensure that only forward slashes are used as path separators on your input to chokidar.
