### ISSUE TITLE
Referenced dependency 'fs' is no longer available on npm

### ISSUE THREAD

**Issue by ColinLaws** [paulmillr/chokidar#672]
## Description

I just encountered an issue while running my webpack watcher script that was thrown from chokidar. Once I browsed to the location of the error, I realized that the fs object that was suppose to be pulled in with require('fs') could not be found, as the fs package is no longer available via npm. 

## Proposed Solution

I do not want to come off as naive, and I am sorry if this issue is very obvious to all of you experienced devs working on chokidar, but from what I've found, there is an alternative package that is being used as a drop-in replacement for fs called 'graceful-fs'.

I recommend that nodefs-handler.js and fsevents-handler.js both be updated to instead use the graceful-fs package as a substitute to the now unavailable fs package.

Sorry if this post was a bit hacked, this is my first issue I have ever submitted and tried to give a solution. Thanks for any help.

**Comment by es128** [comment]
fs is a module from [node’s core](https://nodejs.org/api/fs.html), and therefore is not on npm - but you can rest assured it will always remain available in node. Webpack is supposed to have shims for the node apis, but obviously running in a browser is different - leading to the question: what need do you have for a file watcher in a web app that can’t really interact with the file system?

#572 contains some info about using graceful-fs if you desire, but I wouldn’t advise it if you don’t understand your problem well and are just trying random things and crossing your fingers.

Feel free to open a new issue after you get a clearer idea of what your problem is, or you can try stackoverflow if you’re looking for more general guidance and don’t have an actual chokidar issue to report.

**Comment by ColinLaws** [comment]
I am using a file watcher for browsersync while developing. Running npm run watch resulted in an error in which the reference to the fs module in both files for chokidar threw an exception. This was on a clean install of a project for npm. I dug around in the code to look for the reference, and when I saw that it was referencing an empty package, I imagined that the package was ripped from npm. Just looking out for the community.

I appreciate the explanation, and apologize for the confusion. Like I said, I knew it had to be something you all knew.

**Comment by es128** [comment]
Chokidar running thru webpack for the sake of browsersync sounds like something is misconfigured somewhere. You don’t want your dev and build tools compiled in with your app code.

**Comment by ColinLaws** [comment]
Hm. Must have been a dependency that I added. I assumed it was the file watcher for webpack's watch script because I thought that chokidar was a wrapper around the node file watcher, and this made it easy for someone to watch for changes to a file. Must have been a package that I added that is referencing your code. Don't mean to clutter up the chokidar board with off-topic conversation, thanks for helping me understand the issue I encountered.
