### ISSUE TITLE
does not work in ubuntu 16.04

### ISSUE THREAD

**Issue by juzhen21510** [paulmillr/chokidar#674]
OS:ubuntu 16.04 
node:v6.11.3

I have a test.js like this
`var hot = function() {`
`       var chokidar = require('chokidar');`
`        var watcher = chokidar.watch('./../../lib/modules_config2.json', {persistent:true});`
`        watcher.on('change', function(path){`
`     delete require.cache[require.resolve(path)];`
`        var now = require(path);`
`            console.log(path);`
`            console.log(now.faraday.module);`
`        })`
`}`
`hot();`

The whole project is like this:
`boston-terrier2/`
`├── erizo_controller`
`│         └── erizoAgent`
`│                             └── test.js`
`├── lib`
`│       └── modules_config2.json`
`└── package.json`

when I put this project in /tmp, when I run node test.js and change modules_config2.json, it works well
But when I put this project in other directory like /data/system, it triggers once change, then nothing happens  any more when I change modules_config2.json

-----------------------------------------------------------------------------------------
And I add the listener "raw"

I found, when project under /tmp/system , then change the target file , two event printed:
Raw event info: change modules_config2.json { watchedPath: '../../lib/modules_config2.json' }
Raw event info: change modules_config2.json { watchedPath: '../../lib/modules_config2.json' }
when under /data/system, four event printed:
Raw event info: rename modules_config2.json { watchedPath: '../../lib/modules_config2.json' }
Raw event info: change modules_config2.json { watchedPath: '../../lib/modules_config2.json' }
Raw event info: rename modules_config2.json { watchedPath: '../../lib/modules_config2.json' }
Raw event info: rename modules_config2.json { watchedPath: '../../lib/modules_config2.json' }

Any way, /tmp/system one worked, /data/system one not

**Comment by es128** [comment]
Try `usePolling: true`

**Comment by juzhen21510** [comment]
It will lead to high CPU utilization? 
And I am still confused why it worked under /tmp, other directories not.

**Comment by es128** [comment]
It won’t cause noticeably high cpu utilization for one file. Try it. 

You haven’t offered any clues about the reason for the differences you’ve observed in different directories. I don’t know.

**Comment by juzhen21510** [comment]
Thx any way, will notify U if I find any clues

**Comment by RussCoder** [comment]
For your information, I had a kind of the same issue.

I had to monitor files being updated over FTP from a remote server. It turned out, that actually chokidar (I use 0.3.3 version) fired `change` event and I tried to `fs.readFile` at once, and it returned an empty string due to which my code silently failed.
After I added 

```
  awaitWriteFinish: {
    stabilityThreshold: 500,
    pollInterval: 100
  },
```

to the watcher config, everything started to work properly.

It seems to me that when I write a file via `fs.writeFile()` a `change` event occurs after it has been written down, but when it is transferred over FTP, a change event occurs when a file is empty, at the very beginning of the writing process. 

I found this issue, because initially I also thought the problem is in Ubuntu and chokidar, so I decided to leave here this note.
