### ISSUE TITLE
On windows, when watch .\somedir\*.txt, no files found

### ISSUE THREAD

**Issue by NijiharaTsubasa** [paulmillr/chokidar#722]
This broke on Windows and chokidar@2.0.3, but used to work in chokidar@1.7.0: 

` chokidar.watch('.\\somedir\\*.txt')  `

This also doesn't work:

` chokidar.watch('.\\somedir\\')  `

But both of the following works: 

` chokidar.watch('.\\somedir') ` (without the \\*.txt)

` chokidar.watch('.\\somedir/*.txt') ` (change the last backslash to slash)

My real case is, I used `path.join` to join a path and `'*.txt'`, then passed it to `chokidar.watch`, and it won't find any file after I upgraded chokidar from 1.7.0 to 2.0.3

I think this is a problem since you can't make path.join output slashes instead of backslashes on Windows...

**Comment by NijiharaTsubasa** [comment]
This also doesn't work

`chokidar.watch('D:\\some/absolute/path/*.txt')`

Have to replace the first backslash to slash

**Comment by doowb** [comment]
The latest version of chokidar is more strict on the glob patterns that are passed in. Since `\` is a valid escape character for a glob pattern, windows file paths are not accepted as glob patterns. You should use the [`cwd` option](https://github.com/paulmillr/chokidar#path-filtering) instead of using `path.join`.

`chokidar.watch('*.txt', { cwd: 'D:\\some\\absolute\\path' });`

**Comment by es128** [comment]
Thanks @doowb.

@NijiharaTsubasa you either need to stop combining backslash path separators with your glob patterns or pin your version of chokidar to an earlier one that was forgiving of that and also didn't allow for more advanced glob syntax such as character escaping.
