### ISSUE TITLE
Incorrect behaviour of exclude pattern

### ISSUE THREAD

**Issue by eGavr** [paulmillr/chokidar#724]
Hi!

Here is a minimal case:

FS:

```
folder/
    node_modules/
        .bin/
            file.js
    index.js
```

```js
const chokidar = require('chokidar');
const watcher = chokidar.watch(['./folder', '!node_modules/**']);

watcher.on('add', path => console.log(path));
```

Output:

```
folder/index.js
folder/node_modules/.bin/file.js
```

But should be:

```
folder/index.js
```

I can not use `ignored` option in order to skip dotfiles, bacause I do not want to ignore them, but I need to ignore all files in `node_modules`

Thanks.

**Comment by es128** [comment]
Looks like you intended that second pattern to look more like `!./folder/node_modules/**`

**Comment by eGavr** [comment]
Sorry, incorrect example..

I use the following:

```js
const chokidar = require('chokidar');
const watcher = chokidar.watch(['./folder', '!./folder/node_modules/**']);

watcher.on('add', path => console.log(path));
```

But the result is still incorrect :(

**Comment by eGavr** [comment]
dotfiles are not ignored :(

**Comment by eGavr** [comment]
The problem is that you use `anymatch` which uses `mocromatch` with the switched off option `dot`, so dotfiles are ignored in your package.

**Comment by eGavr** [comment]
ping  :)

**Comment by es128** [comment]
I'm uncertain of what you're looking for. If you want to be able to pass options to micromatch through chokidar config then I suggest you open a new issue with a clearer explanation.

**Comment by bpasero** [comment]
@es128 this should be reopened imho. The following is a simple example where the ignore pattern does not work:

```js
let chokidar = require("chokidar");

var watcher = chokidar.watch('<some folder with package.json>, {
    ignoreInitial: true,
    ignored: '**/node_modules/**',
    persistent: true
  });

  watcher.on('all', console.log)
```

Run `npm install` in that folder and get tons of output from any path that contains a leading ".". NPM seems to have introduced a `.staging` folder a while ago so basically now every file will show up in the event handler of chokidar due to this issue. 

The FiX is to use `{ dot: true }` in `anymatch` when using `micromatch` (e.g. [here](https://github.com/micromatch/anymatch/blob/master/index.js#L14)).
