### ISSUE TITLE
yarn + node 10+ support by updating upath dependency

### ISSUE THREAD

**Issue by ahmadnassri** [paulmillr/chokidar#775]
the latest version of `chokidar` is relying on `upath` `v1.0.5`

this results in errors on Node `v10+` when running `yarn`:

```
error upath@1.0.4: The engine "node" is incompatible with this module. Expected version ">=4 <=9". Got "11.1.0"
error Found incompatible module
```

this has been addressed by the `upath` maintainers: https://github.com/anodynos/upath/issues/24

a version bump to `1.1.0` would resolve this issue.

**Comment by phated** [comment]
They removed node <4 support. Can't update yet.

I'd suggest not installing with yarn - npm never explodes with incompatible engines.

**Comment by useafterfree** [comment]
`yarn --ignore-engines install` also works until this is fixed.

**Comment by Prior99** [comment]
webpack is depending on chokidar and hence it isn't possible for projects depending on webpack to switch to node 10+. Isn't it possible to upgrade and discontinue node 4 support or replace upath with another dependency?

**Comment by oskarolsson-jimdo** [comment]
> They removed node <4 support. Can't update yet.

@phated Reading through the release-log of upath it seems `^1.0.5` used by chokidar has neither more or less support for node<4. In fact it appears that the only thing that was removed was the upper limit of node versions to enable users to use node 10.x and newer.

Here are the specific commits made to upath between 1.0.5 and 1.1.0: https://github.com/anodynos/upath/compare/2b181f4f1a19f2c919e452e5b837d4719d93118c...2a26dec09bc4d7dcb1bc49ca26f62c0ab42b3d4d

None of the changes look like they would cause problems on node<4. 

This issue is holding back a lot of users from upgrading to newer versions of node. Please reconsider bumping to a newer version.

**Comment by Bibliofile** [comment]
Node 4 has been EOL for nearly a year now... not LTS support.... EOL... why can't anyone still running Node 4 just live with an old version of chokidar?

**Comment by paulmillr** [comment]
We're going to drop nodes older than version 8 in 2.2 or 3.0; soon.

**Comment by phated** [comment]
@paulmillr 👍 that should be a major bump, since it'll break people.
