### ISSUE TITLE
Access time/Modification time check breaks file watching with high latency file uploads

### ISSUE THREAD

**Issue by jeremycondon** [paulmillr/chokidar#799]
**Describe the bug**
We use Rsync to copy files from our local machines to a remote host.  Using Rsync -apz includes copying local access time and modification time up to the remote host.  As of the change in [2.1.1](https://github.com/paulmillr/chokidar/commit/c5f9718f868c067253636d7a8616141c3606e08a#diff-a211b3645e08f044b3d64f65bbcabac9) the Atime and Mtime when Rsyncing are high enough to skip the `this._emit('change', file, newStats);`

**Versions (please complete the following information):**
 - Chokidar version 2.1.1
 - Node version 8.x.x and 11.x.x tested
 - OS version: Ubuntu 16.04

**To Reproduce**
We are currently running `webpack --watch` on an EC2 instance and using `rsync -apz` to copy files up.  Changing to `rsync -rlopgDz` stops syncing the time stamps and the problem gets resolved.

**Expected behavior**
I would expect that these files would be treated as changed as they were in prior releases.

**Comment by paulmillr** [comment]
@markablov we need to resolve the issue or have the change reverted

**Comment by markablov** [comment]
@paulmillr i am going to track previous stats object (`prevStats = stats`) and add additional check if `prevStats.mtime != newStats.mtime` so it should handle such situations. Sounds ok to you?

**Comment by paulmillr** [comment]
yes

**Comment by markablov** [comment]
@paulmillr https://github.com/paulmillr/chokidar/pull/800

@jeremycondon issue is fixed, but i have noticed another caveat with rsync approach:
1. Modify file and make rsync
2. `chokidar` fires `change` event
3. Again modify file and perform another rsync
4. `chokidar` is not receiving FS notification (`fs.watch` is not calling callback).

May be it's because i was using local directories as source and destination for my tests, but still want to warn you about this ;)

**Comment by jeremycondon** [comment]
Much appreciated!  Nice PR on that.  I'll let my team know to keep an eye out for issues like that, I haven't heard any issues on my side yet.
