### ISSUE TITLE
not possible to watch for file creation only

### ISSUE THREAD

**Issue by date80** [paulmillr/chokidar#966]
Maybe this is not a bug but a misunderstanding on my side:

On a Ubuntu machine I have a folder with ~100.000 files and I want to be informed whenever a new file is added (I do NOT care when an already existing file is modified).

I've googled a lot the last few evenings but I cannot see how this can be achieved with chokidar in an efficient way. Whenever I start to watch the folder I get errors like `Error: ENOSPC: System limit for number of file watchers reached, watch '<FILENAME>'`.
Isn't it possible to use `chokidar.watch` in a way that no file watcher is added to each file inside a folder but just the folder itself is watched for newly added files?

**Versions:**
 - Chokidar version 3.3.1
 - Node version v10.18.0
 - OS version: Ubuntu 16.04

**Comment by paulmillr** [comment]
See readme for info on how to handle this problem.

**Comment by date80** [comment]
@paulmillr
I know that there is a hint in the readme describing how the number of file handles can be increased on Linux systems. Actually it doesn't seem sensible to me to have thousands of open file handles if I'm not interested in changes to these files (I'm interested in file creations only). Just wanted to know if what I want to achieve is not a use case supported by your lib...

**Comment by paulmillr** [comment]
There is no difference on Linux, in any case you will need to track directories for file changes, and the number of directories may be larger, than system limit.

On macos, chokidar can use one handler for e.g. 100,000 files, which makes it very effective.

**Comment by hi2u** [comment]
@paulmillr ... just a question on this...

> There is no difference on Linux, in any case you will need to track directories for file changes, and the number of directories may be larger, than system limit.

I wasn't too sure what you meant with "and the number of directories may be larger" and if that was just referring to when people need to watch multiple dirs?  Or also relevant on a single folder with lots of files?...

My use case is that:

* I'm just watching one directory (not recursively) on Linux
* I only need chokidar to notify when a file is moved into this directory (it's an atomic `mv` from a different dir on the same filesystem)

In this situation, does Chokidar on Linux require that every single file already in the dir be watched?  I'm running into RAM usage issues when I start my app and there's already many files in there, i.e. about 80k existing files before running my app.

I've already updated the kernel option:

    echo fs.inotify.max_user_watches=524288 | sudo tee -a /etc/sysctl.conf && sudo sysctl -p

So I'm not hitting the kernel watch limit, but I'm just running out of RAM due to all the pre-existing files being watched, when I don't need them to be.  I just need the dir itself watched for files being moved into it.

I'm using `ignoreInitial: true`, and also tried setting `depth` to `0` and `1`.

Is there any way for me to adjust settings with chokidar to avoid this memory use issue?  Or is there no way to use less RAM / not watch all the files in this situation on Linux at all?

Sorry if it sounds like I'm asking the exact same thing as @date80 again... I'm just trying to clarify because when you said "and the number of directories may be larger" it sounds like you're talking about watching multiple dirs rather than just the one?

**Comment by paulmillr** [comment]
> does Chokidar on Linux require that every single file already in the dir be watched

Yes

**Comment by gauss256** [comment]
I had the same need as the OP and couldn't avoid the `ENOSPC` error when using chokidar, because it watches every file in the directory.

I used `fs.watch` instead. ChatGPT wrote the following sample code. I adapted it to my code and it is working well on Ubuntu 20.04. If you specify a directory to `fs.watch`, it won't create watchers for files that are already in that directory.

```
const fs = require('fs');
const path = require('path');

const watchDirectory = (directoryPath) => {
  fs.watch(directoryPath, (eventType, filename) => {
    if (eventType === 'rename' && filename) {
      const filePath = path.join(directoryPath, filename);

      fs.access(filePath, fs.constants.F_OK, (err) => {
        if (!err) {
          console.log(`File added in ${directoryPath}: ${filename}`);
        }
      });
    }
  });
};

const directoryPaths = [
  '/path/to/your/first/directory',
  '/path/to/your/second/directory',
  '/path/to/your/third/directory',
  // Add more directory paths as needed
];

directoryPaths.forEach((dirPath) => {
  watchDirectory(dirPath);
});
```

**Comment by timelord666** [comment]
Why does chokidar requires to watch every file in directory if i'm interested only in changes to directory, like added file? Would be pretty cool to have that setting or warning about it.
